Github: https://github.com/EdwardChhun/CS178

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
cd drive/MyDrive/UCI/178/project/

/content/drive/MyDrive/UCI/178/project

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder


seed = 1234
np.random.seed(seed)

In [20]:
"""
Splitting the data
"""

# diabities = pd.read_csv("diabetic_data.csv")
# data_train, data_test = train_test_split(diabities, train_size=.9, test_size=.1, shuffle=True, random_state=seed)

# pd_train = pd.DataFrame(data_train)
# pd_test = pd.DataFrame(data_test)

# pd_train.to_csv("training_data.csv")
# pd_train.to_csv("testing_data.csv")

'\nSplitting the data\n'

In [21]:
df = pd.read_csv("training_data.csv")

print(df.shape)
df.head()

(91589, 51)

,Unnamed: 0,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,83148,259912530,88114716,Caucasian,Female,[60-70),?,1,6,7,...,No,Up,No,No,No,No,No,Ch,Yes,NO
1,8067,37094196,604017,Caucasian,Female,[60-70),?,1,1,7,...,No,No,No,No,No,No,No,Ch,Yes,NO
2,19623,69819834,3401055,AfricanAmerican,Female,[40-50),?,1,6,7,...,No,No,No,No,No,No,No,No,No,>30
3,77236,234245010,71780013,Caucasian,Male,[70-80),?,2,6,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
4,55677,160693860,82716489,Caucasian,Female,[80-90),?,6,3,7,...,No,No,No,No,No,No,No,No,No,>30

In [22]:
"""
Replacing the missing data with NaN
"""

missing_cols = ['race', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'gender']

column_to_missing = {}
for col in missing_cols:
    if col != 'gender':
        column_to_missing[col] = '?'
    else:
        column_to_missing[col] = 'Unknown/Invalid'

# print(column_to_missing)

for col, miss_val in column_to_missing.items():
    df[col] = df[col].replace(miss_val, np.nan)

df.isnull().sum()

Unnamed: 0                      0
encounter_id                    0
patient_nbr                     0
race                         2044
gender                          2
age                             0
weight                      88727
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  36237
medical_specialty           44911
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         19
diag_2                        332
diag_3                       1292
number_diagnoses                0
max_glu_serum               86780
A1Cresult                   76267
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [35]:
"""
Replace NaN Race entries with mode
"""

# print(df['race'].unique())
mode = df['race'].mode()[0]
df['race'] = df['race'].fillna(mode)

In [45]:
"""
Replace NaN Weight entries with median
"""

# print(df['weight'].unique())
sorted_unique_values = ['[0-25)', '[25-50)', '[50-75)', '[75-100)', '[100-125)',
                        '[125-150)', '[150-175)', '[175-200)' '>200']

median = sorted_unique_values[len(sorted_unique_values) // 2]
df['weight'] = df['weight'].fillna(median)

In [50]:
"""
Replace NaN payer_code entries with mode
"""

# print(df['payer_code'].unique())
mode = df['payer_code'].mode()[0]
df['payer_code'] = df['payer_code'].fillna(mode)

In [54]:
"""
Replace NaN medical_specialty entries with mode
"""

# print(df['medical_specialty'].unique())
mode = df['medical_specialty'].mode()[0]
df['medical_specialty'] = df['medical_specialty'].fillna(mode)

In [58]:
"""
Replace NaN max_glu_serum entries with median
"""

# print(df['max_glu_serum'].unique())
sorted_unique_values = ['Norm', '>200', '>300']

median = sorted_unique_values[len(sorted_unique_values) // 2]
df['max_glu_serum'] = df['max_glu_serum'].fillna(median)

In [ ]:
"""
Replace NaN A1Cresult entries with median
"""

# print(df['A1Cresult'].unique())
sorted_unique_values = ['Norm', '>7', '>8']

median = sorted_unique_values[len(sorted_unique_values) // 2]
df['A1Cresult'] = df['A1Cresult'].fillna(median)

In [71]:
"""
Drop rows with missing gender, diag_1, diag_2, and diag_3 as they account
for a very small portion of the data
"""

df.dropna(subset=['gender', 'diag_1', 'diag_2', 'diag_3'], inplace=True)

In [72]:
df.isnull().sum()

Unnamed: 0                  0
encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [73]:
df.head()

,Unnamed: 0,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,83148,259912530,88114716,Caucasian,Female,[60-70),[100-125),1,6,7,...,No,Up,No,No,No,No,No,Ch,Yes,NO
1,8067,37094196,604017,Caucasian,Female,[60-70),[100-125),1,1,7,...,No,No,No,No,No,No,No,Ch,Yes,NO
2,19623,69819834,3401055,AfricanAmerican,Female,[40-50),[100-125),1,6,7,...,No,No,No,No,No,No,No,No,No,>30
3,77236,234245010,71780013,Caucasian,Male,[70-80),[100-125),2,6,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
4,55677,160693860,82716489,Caucasian,Female,[80-90),[100-125),6,3,7,...,No,No,No,No,No,No,No,No,No,>30